#!/usr/bin/env python
import json
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
import api

class VCAPPoller(object):
    _target = None
    _data = None

    def __init__(self, target, email, password):
        self._target = api.Target(target, email, password)

    def getData(self):
        if self._data:
            return self._data

        self._data = {
            'info': self._target.info,
            'apps': self._target.apps,
            'systemServices': self._target.systemServices,
            'provisionedServices': self._target.provisionedServices,
        }

        # app_uris exists under info/limits, but not info/usage. Resolving.
        self._data['info']['usage']['app_uris'] = 0

        for app in self._data['apps']:
            name = app['name']

            # See note about app_uris above.
            self._data['info']['usage']['app_uris'] += len(app['uris'])

            app['instances'] = self._target.getAppInstances(name)['instances']

            app_stats = self._target.getAppStats(name)

            for instance in app['instances']:
                instance['stats'] = app_stats[str(instance['index'])]

        return self._data

    def printJSON(self):
        print json.dumps(self.getData())


if __name__ == "__main__":
    target = email = password = None
    try:
        target, email, password = sys.argv[1:]
    except ValueError:
        print >> sys.stderr, "Usage: {0} <target> <email> <password>".format(
            sys.argv[0])
        sys.exit(1)

    poller = VCAPPoller(target, email, password)
    poller.printJSON()

